iMac-admin.local-up

diff --git a/lib-git b/lib-git
--- a/lib-git
+++ b/lib-git
@@ -1,4 +1,3 @@
-#!/bin/bash
 # TODO: gids for commit - last ~1 ~2
 # get all branches from remote (after clone)
 
@@ -21,7 +20,9 @@ case "$UTILS_GIT_THE_OS" in
 	*)
 		# fail !
   esac
+
 alias log_print='[ "$UTILS_GIT_TRACE" == "1" ] && echo -e 1>&2 '
+alias error='cmd_utils_git_error'
 
 tab="%x09"
 git_red="%C(red)" # "%x1b[31m"
@@ -50,8 +51,8 @@ REFNAME="%d"
 
 cmd_utils_git_wrapper(){
 	local cmd_one="$1"
-
 	local utils_git_timestamp_current
+	UTILS_GIT_TRACE=0
 	case "$UTILS_GIT_THE_OS" in
 		MINGW*)
 			utils_git_timestamp_current=`stat -c %y $HOME_UTILS_GIT/lib-git`
@@ -73,7 +74,7 @@ cmd_utils_git_wrapper(){
 	local params
 	while :
 	do
-		log_print "arg: $1"
+		#log_print "arg: $1"
 		case "$1" in
 			#-h|--help) ;;
 			-v) UTILS_GIT_TRACE=1 ;;
@@ -83,9 +84,15 @@ cmd_utils_git_wrapper(){
 		  esac
 		shift
 	done
+	log_print "cmd:     $cmd_one"
 	log_print "params: $params"
 	eval $cmd_one "$params" #"$@*"
-	# UTILS_GIT_TRACE=0
+	}
+
+cmd_utils_git_error(){
+	msg="$*"
+	log_print "msg: $msg"
+	echo -e "${red}$msg ${norm}"
 	}
 
 find_branch() {
@@ -854,19 +861,18 @@ cmd_git_remotes_show(){ 				# girs
 		  fi
 	  done
 	}
-cmd_git_remotes_show_detail(){ 				# gird
+cmd_git_remotes_show_detail(){ 				# girx
 	#git remote -v
-	remotes=$(git remote show)
-	#echo remotes: $remotes
-	for name in $remotes; do 
-		if [[ "$1" != "" ]]; then
-			remote=$(echo $name | grep "$1")
-			#echo remote: $remote
-			[[ "$name" == "$remote" ]] && git remote show $name
-		  else
-		  	git remote show $name
-		  fi
-	  done
+	if [[ "$1" != "" ]]; then
+		git remote show $1
+	  else
+		remotes=$(git remote show)
+		log_print remotes: $remotes
+		for remote in $remotes; do 
+			log_print "remote: $remote"
+			[[ "$remote" == "$remote" ]] && git remote show $remote
+		  done
+	  fi
 	# when - error: invalid branch.master.merge; cannot rebase onto > 1 branch
 	# run gect and replace for [branch "ex.master"] 
 	# 'rebase = true' to 'rebase = false'
@@ -892,7 +898,73 @@ cmd_git_remote_rename(){				# girn
 	  fi
 	}
 cmd_git_remote_set_default(){ 				# giru
+	[ "$1" == "" ] && error "remote alias is missed (1st param)" && return
 	git branch --set-upstream-to $1/$(current_branch)
+	return
+
+	remote_alias=$1
+	log_print "remote_alias: $remote_alias"
+	if [ "$remote_alias" == "" ]; then
+		echo -e "${red}remote alias is missing${norm}"
+		return
+	  fi
+	remote_url=`cat $HOME/.utils-git/remotes/$remote_alias` 2> /dev/null
+	if [ "$remote_url" == "" ]; then
+		echo -e "${red}remote alias '$HOME/.utils-git/remotes/$remote_alias' not found${norm}"
+		return
+	  fi
+	git remote remove $remote_alias
+
+	}
+cmd_git_remote_delete(){				# gird
+	# delete remote
+	[[ "$1" == "" ]] && echo "[DELETE REMOTE] name is missed !" && return
+	#remotes=$(ls -1)
+	remote=$1
+	# echo curr_remote: $curr_remote
+	if [[ "$remote" == "all" ]]; then
+		remotes=$(git remote show)
+		#echo remotes: $remotes
+		remotes_cnt=$(echo -e "$remotes" | wc -l)
+		#echo remotes_cnt: $remotes_cnt
+		if [[ $remotes_cnt -eq 1 ]]; then
+			git remote remove $remotes
+		  else
+		  	echo -e "${red}no one remote defined${norm}"
+		  fi
+	  else
+		git remote remove $remote
+	  fi
+	}
+cmd_git_remote_add(){					# gira
+	remote_alias=$1
+	#remote_url=$2
+	[ "$remote_alias" == "" ] && error "remote alias is missed (1st param)" && return
+	#[ "$remote_url" == "" ] && error "remote url is missed (2nd param)" && return
+	#git remote add $1 $2
+	#return
+	log_print "remote_alias: $remote_alias"
+	remote_url=`cat $HOME/.utils-git/remotes/$remote_alias` 2> /dev/null
+	[ "$remote_url" == "" ] && error "remote alias is missed (1st param)" && return
+
+	log_print "remote_url: $remote_url"
+	remote_url=`eval echo "$remote_url"`
+	log_print "remote_url: $remote_url"
+	if [ "$remote_url" == "" ]; then
+		echo -e "${red}remote alias '$HOME/.utils-git/remotes/$remote_alias' not found${norm}"
+		return
+	  fi
+		#if($url =~ /([^:]*:\/\/)?([^\/]+\.[^\/]+)/g) {
+		#  print $2;
+		#}
+		return
+	prj_name=$(basename `git rev-parse --show-toplevel`)
+	log_print "git remote add $remote_alias $remote_url/$prj_name.git"
+	git remote add $remote_alias "$remote_url/$prj_name.git"
+	git ls-remote "$remote_url/$prj_name.git" 2> \dev\null
+	#if [ $? != 0 ]; then
+		#curl -u $GITUSER:$PASSWORD https://api.github.com/user/repos -k -d '{"name":"'${PWD##*/}'"}' -k -s | jq '.[] | .name + if .private then " - private" else "" end'
+		#curl --user $GITUSER:$PASSWORD https://api.bitbucket.org/1.0/repositories/ --data name=${PWD##*/} --data is_private='true' -k -s | jq ''
 	}
 
 cmd_git_status_with_untracked(){ 			# gis
@@ -953,9 +1025,9 @@ cmd_git_pull(){ 					# gul
 			echo -e "${red}Remote is absent or ambigiouse$norm" 1>&2 
 			# return
 		  else
-			echo -e "[utils-git] ${red}FETCH${norm} from ${green}$curr_remote/$curr_branch$norm"  #-u
+			echo -e "[utils-git] ${red}FETCH${norm} $green$curr_remote/$curr_branch$norm"
 			# git pull --stat --no-rebase #--all --quiet
-			git fetch -vv "$curr_remote" "$curr_branch" # vv -  отслеживаемые ветки
+			git fetch -vv --quiet "$curr_remote" "$curr_branch" # vv -  отслеживаемые ветки
 			echo "result (\$?): $?"
 			echo -e "[utils-git] ${red}MERGE${norm} with $green$curr_remote/$curr_branch$norm"  #-u
 			git merge "$curr_remote"/"$curr_branch"
@@ -998,7 +1070,7 @@ cmd_git_push(){ 					# gus
 			echo -e "${red}Remote is absent or ambigiouse$norm" 1>&2 
 			# return
 		  else
-			echo -e "git ${red}PUSH${norm} to ${red}$curr_remote$norm: $green$curr_branch$norm"  #-u
+			echo -e "[utils-git] ${red}PUSH${norm} to ${green}$curr_remote/$green$curr_branch$norm"  #-u
 			git push "$curr_remote" "$curr_branch" #all --all
 		  fi
 	  else
@@ -1006,7 +1078,7 @@ cmd_git_push(){ 					# gus
 		for name in $remotes; do 
 			if [[ "$name" == "$one_remote" || "$one_remote" = "all" ]]; then
 				# echo -e "${red}$name$norm"
-				echo -e "git ${red}PUSH${norm} to ${red}$name$norm: $green$curr_branch$norm"  #-u
+				echo -e "[utils-git] ${red}PUSH${norm} to ${green}$name/$green$curr_branch$norm"  #-u
 				git push "$name" "$curr_branch" #all --all
 				#git branch --set-upstream-to <remote-name>
 			  #else
@@ -1037,46 +1109,4 @@ cmd_git_stash_list(){ 					# gstl
 	}
 cmd_git_stash_pop(){ 					# gsp
 	git stash pop
-	}
-
-cmd_git_remote_add(){					# gira
-	remote_alias=$1
-	log_print "remote_alias: $remote_alias"
-	if [ "$remote_alias" == "" ]; then
-		echo -e "${red}remote alias is missing${norm}"
-		return
-	  fi
-	remote_url=`cat $HOME/.utils-git/remotes/$remote_alias` 2> /dev/null
-	log_print "remote_url: $remote_url"
-	remote_url=`eval echo "$remote_url"`
-	log_print "remote_url: $remote_url"
-	if [ "$remote_url" == "" ]; then
-		echo -e "${red}remote alias '$HOME/.utils-git/remotes/$remote_alias' not found${norm}"
-		return
-	  fi
-		#if($url =~ /([^:]*:\/\/)?([^\/]+\.[^\/]+)/g) {
-		#  print $2;
-		#}
-		return
-	prj_name=$(basename `git rev-parse --show-toplevel`)
-	log_print "git remote add $remote_alias $remote_url/$prj_name.git"
-	git remote add $remote_alias "$remote_url/$prj_name.git"
-	git ls-remote "$remote_url/$prj_name.git" 2> \dev\null
-	#if [ $? != 0 ]; then
-		#curl -u $GITUSER:$PASSWORD https://api.github.com/user/repos -k -d '{"name":"'${PWD##*/}'"}' -k -s | jq '.[] | .name + if .private then " - private" else "" end'
-		#curl --user $GITUSER:$PASSWORD https://api.bitbucket.org/1.0/repositories/ --data name=${PWD##*/} --data is_private='true' -k -s | jq ''
-	}
-cmd_git_remote_del(){					# gire
-	remote_alias=$1
-	log_print "remote_alias: $remote_alias"
-	if [ "$remote_alias" == "" ]; then
-		echo -e "${red}remote alias is missing${norm}"
-		return
-	  fi
-	remote_url=`cat $HOME/.utils-git/remotes/$remote_alias` 2> /dev/null
-	if [ "$remote_url" == "" ]; then
-		echo -e "${red}remote alias '$HOME/.utils-git/remotes/$remote_alias' not found${norm}"
-		return
-	  fi
-	git remote remove $remote_alias
 	}
