stand-up

diff --git a/lib-git b/lib-git
--- a/lib-git
+++ b/lib-git
@@ -672,21 +672,21 @@ cmd_git_last_n_commits_stat_with_hash(){
 	#git log --numstat --pretty --oneline 0f5d22e..HEAD -- <filename>
 	}
 
-cmd_git_branch_merge_after_pull(){
+cmd_git_branch_merge_after_pull(){ # gim
 	source_branch=$(find_branch "$1") #; echo branch: $branch
 	exitcode=$?
-	[ $exitcode -ne 0 ] && echo not found && exit
+	[ $exitcode -ne 0 ] && echo not found && return
 
 	currbranch=$(current_branch)
 	echo "from '$source_branch' to '$currbranch'"
 
 	echo "Pull '$source_branch'"
 	#git checkout $branch
-	gib $source_branch || exit
-	gul || exit
+	gib $source_branch || return
+	gul || {gib source_branch} # || return
 
 	#git checkout $source_branch
-	gib $currbranch || (echo "FAIL! ANOTHER BRANCH !!" && exit)
+	gib $currbranch || (echo "FAIL! ANOTHER BRANCH !!" && return)
 
 	#echo exitcode: $exitcode
 	#echo current_branch: $(current_branch)
@@ -697,12 +697,12 @@ cmd_git_branch_merge_after_pull(){
 	git merge $source_branch
 	#echo done
 	}
-cmd_git_branch_merge_with_local(){
+cmd_git_branch_merge_with_local(){ # giml
 	branch=$(find_branch "$1") # result; echo result:$result; branch=${result}
 	exitcode=$?
 	#echo exitcode: $exitcode
 	#echo current_branch: $(current_branch)
-	[ $exitcode -ne 0 ] && echo not found && exit
+	[ $exitcode -ne 0 ] && echo not found && return
 	#[ $exitcode -eq 1 ] && echo "Find branch by $1*: AMBIGUOUS" && exit
 	#[ $exitcode -eq 2 ] && echo "Find branch by *$1*: NOT FOUND" && exit
 	#[ $exitcode -eq 3 ] && echo "Find branch by *$1*: AMBIGUOUS" && exit
@@ -710,7 +710,7 @@ cmd_git_branch_merge_with_local(){
 	git merge $branch
 	#echo done
 	}
-cmd_git_branch_target_branch_with_this_after_pull(){
+cmd_git_branch_target_branch_with_this_after_pull(){ # gimto
 	currbranch=$(current_branch)
 	echo currbranch: $currbranch
 
@@ -720,16 +720,16 @@ cmd_git_branch_target_branch_with_this_after_pull(){
 	  # [ $? -eq 0 ] 
 	if [[ "$tobranch" != "" ]]; then
 		git checkout $tobranch
-		  [ $? -ne 0 ] && exit
+		  [ $? -ne 0 ] && return
 		gul # fetch and merge
-		  [ $? -ne 0 ] && exit
+		  [ $? -ne 0 ] && return
 		git merge $currbranch
-		  [ $? -ne 0 ] && exit
+		  [ $? -ne 0 ] && return
 		git checkout $currbranch
 		#gil 7
 	  fi
 	}
-cmd_git_branch_target_local_branch_with_this(){
+cmd_git_branch_target_local_branch_with_this(){ # gimtol
 	currbranch=$(current_branch)
 	echo currbranch: $currbranch
 
@@ -739,9 +739,9 @@ cmd_git_branch_target_local_branch_with_this(){
 	  # [ $? -eq 0 ] 
 	if [[ "$tobranch" != "" ]]; then
 		git checkout $branch
-		  [ $? -ne 0 ] && exit
+		  [ $? -ne 0 ] && return
 		git merge $currbranch
-		  [ $? -ne 0 ] && exit
+		  [ $? -ne 0 ] && return
 		git checkout $currbranch
 		gil 7
 	  fi
